[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    setup: Маркировка для тестов, связанных с настройками API.
    users: Маркировка для тестов, связанных с пользователями.
    games: Маркировка для тестов, связанных с играми.
    wishlists: Маркировка для тестов, связанных со списком желаемого.
    regression: Маркировка для регрессионных тестов.
